# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from fsm_proto import fsm_cleaner_pb2 as fsm__proto_dot_fsm__cleaner__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in fsm_proto/fsm_cleaner_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FSMCleanerStub(object):
    """The FSMCleaner service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RemoveFile = channel.unary_unary(
                '/FSMCleaner/RemoveFile',
                request_serializer=fsm__proto_dot_fsm__cleaner__pb2.RemoveFileRequest.SerializeToString,
                response_deserializer=fsm__proto_dot_fsm__cleaner__pb2.RemoveFileResponse.FromString,
                _registered_method=True)


class FSMCleanerServicer(object):
    """The FSMCleaner service definition.
    """

    def RemoveFile(self, request, context):
        """RPC service with request/response information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FSMCleanerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RemoveFile': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveFile,
                    request_deserializer=fsm__proto_dot_fsm__cleaner__pb2.RemoveFileRequest.FromString,
                    response_serializer=fsm__proto_dot_fsm__cleaner__pb2.RemoveFileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FSMCleaner', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('FSMCleaner', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FSMCleaner(object):
    """The FSMCleaner service definition.
    """

    @staticmethod
    def RemoveFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FSMCleaner/RemoveFile',
            fsm__proto_dot_fsm__cleaner__pb2.RemoveFileRequest.SerializeToString,
            fsm__proto_dot_fsm__cleaner__pb2.RemoveFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
