"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class AddNewFileRequest(google.protobuf.message.Message):
    """The request message containing file path"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PATH_FIELD_NUMBER: builtins.int
    path: builtins.str
    def __init__(
        self,
        *,
        path: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["path", b"path"]) -> None: ...

global___AddNewFileRequest = AddNewFileRequest

@typing.final
class AddNewFileResponse(google.protobuf.message.Message):
    """The response message returning if file has been added to search engine"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ADDED_FIELD_NUMBER: builtins.int
    added: builtins.bool
    def __init__(
        self,
        *,
        added: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["added", b"added"]) -> None: ...

global___AddNewFileResponse = AddNewFileResponse
