# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fsm_search.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x66sm_search.proto\"!\n\x11\x41\x64\x64NewFileRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"#\n\x12\x41\x64\x64NewFileResponse\x12\r\n\x05\x61\x64\x64\x65\x64\x18\x01 \x01(\x08\x32\x44\n\tFSMSearch\x12\x37\n\nAddNewFile\x12\x12.AddNewFileRequest\x1a\x13.AddNewFileResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fsm_search_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ADDNEWFILEREQUEST._serialized_start=20
  _ADDNEWFILEREQUEST._serialized_end=53
  _ADDNEWFILERESPONSE._serialized_start=55
  _ADDNEWFILERESPONSE._serialized_end=90
  _FSMSEARCH._serialized_start=92
  _FSMSEARCH._serialized_end=160
# @@protoc_insertion_point(module_scope)
