"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class RemoveFileRequest(google.protobuf.message.Message):
    """The request message containing file path"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PATH_FIELD_NUMBER: builtins.int
    MD5SUM_FIELD_NUMBER: builtins.int
    path: builtins.str
    md5sum: builtins.str
    def __init__(
        self,
        *,
        path: builtins.str = ...,
        md5sum: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["md5sum", b"md5sum", "path", b"path"]) -> None: ...

global___RemoveFileRequest = RemoveFileRequest

@typing.final
class RemoveFileResponse(google.protobuf.message.Message):
    """The response message returning if file has been removed to search engine"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REMOVED_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    removed: builtins.bool
    error: builtins.bool
    def __init__(
        self,
        *,
        removed: builtins.bool = ...,
        error: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error", b"error", "removed", b"removed"]) -> None: ...

global___RemoveFileResponse = RemoveFileResponse
